### ISSUE TITLE
May i ask what environment: ${{ vars.ENVIRONMENT }} used for in Gihtub Action workflow?

### ISSUE THREAD

**Issue by xinatcg** [csye7125-fall2023-group05/ami-jenkins#44]
May i ask what environment: ${{ vars.ENVIRONMENT }} used for in Gihtub Action workflow?

and what I should setup for vars.ENVIRONMENT?

**Comment by sydrawat01** [comment]
Hi @xinatcg, the `vars.ENVIRONMENT` variable is used to differentiate between development, staging and production build of the custom AMI for our Jenkins server image.
We have this configured at organization level rather than repository level since all of our repositories require `development`, `staging` and `production` builds for our CD pipelines.

Once you configure the ENVIRONMENT at the organization level, you can have localized variables in your repositories (like here) to differentiate the AWS credentials required for different environments for your builds.

**Comment by sydrawat01** [comment]
Closing this as resolved. Please feel free to reopen the issue if you still have doubts!
